apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: book-review
data:
  DB_HOST: "book-review-aurora-cluster.cluster-ccn62seuorp0.us-east-1.rds.amazonaws.com"
  DB_NAME: "bookreviewdb"
  DB_PORT: "3306"
  NODE_ENV: "production"
  PORT: "3001"
